spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Bulanden/spring-cloud-config
          serch-paths: respo
          username: Bulanden
          password: caijinfeng520
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka/
