spring:
  application:
    name: hello-spring-cloud-service-admin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka/
