
spring:
  application:
    name: hello-spring-cloud-web-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9080/eureka/
